version: "3.8"

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/app
            - ./pdf_storage:/pdf_storage
        environment:
            - PYTHONUNBUFFERED=1
        networks:
            - pdf-network

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - REACT_APP_API_URL=http://localhost:8000
            - WATCHPACK_POLLING=true # Para hot reload funcionar no Windows/WSL
        depends_on:
            - backend
        networks:
            - pdf-network

networks:
    pdf-network:
        driver: bridge
